OBJS = main.o
TARGET = $(BIN_PATH)/kvh

CFLAGS = $(CFLAGS_STD) $(CFLAGS_COMMON) $(CFLAGS_LCM) $(CFLAGS_APRIL_LCMTYPES)
LDFLAGS = $(LDFLAGS_STD) $(LDFLAGS_COMMON) $(LDFLAGS_LCM) $(LDFLAGS_APRIL_LCMTYPES) -lpthread
DEPS = $(DEPS_STD) $(DEPS_COMMON) $(DEPS_LCM) $(DEPS_APRIL_LCMTYPES)

include $(BUILD_COMMON)


all: $(TARGET)
	@true

$(TARGET): $(OBJS) $(DEPS)
	@$(LD) -o $@ $^ $(LDFLAGS)

clean:
	@rm -rf *.o $(TARGET)
