SRCS = $(shell ls *.c)
OBJS = $(SRCS:%.c=%.o)
TARGET = $(BIN_PATH)/lcm-camera-driver

CFLAGS := $(CFLAGS_STD) $(CFLAGS_COMMON) $(CFLAGS_CAMERA) $(CFLAGS_IMAGESOURCE) $(CFLAGS_APRIL_LCMTYPES) $(CFLAGS_LCM)
LDFLAGS := $(LDFLAGS_STD) $(LDFLAGS_COMMON) $(LDFLAGS_CAMERA) $(LDFLAGS_IMAGESOURCE) $(LDFLAGS_APRIL_LCMTYPES) $(LDFLAGS_LCM)
DEPS := $(DEPS_STD) $(DEPS_CAMERA) $(DEPS_IMAGESOURCE) $(DEPS_APRIL_LCMTYPES) $(DEPS_LCM)

include $(BUILD_COMMON)


all: $(TARGET)
	@/bin/true

$(TARGET): $(OBJS) $(DEPS)
	@$(LD) -o $@ $^ $(LDFLAGS)

clean:
	@rm -rf *.o $(TARGET)
