#!/bin/bash

# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

exec 1>&2
echo "Running" $0
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR=$(dirname "$0")
ACTION="commit"

# Load shared functions
. $DIR/common.sh

# Check and reject commit if binaries are added/modified
echo "Running check_binaries.sh"
. $DIR/check_binaries.sh

