SRCS = $(shell ls *.c)
OBJS = $(SRCS:%.c=%.o)
TARGET = $(BIN_PATH)/apriltag-viewer

CFLAGS := $(CFLAGS_STD) $(CFLAGS_COMMON) $(CFLAGS_VX) $(CFLAGS_IMAGESOURCE) $(CFLAGS_APRIL_LCMTYPES) $(CFLAGS_CAMERA)
LDFLAGS := $(LDFLAGS_STD) $(LDFLAGS_VX) $(LDFLAGS_APRILTAG) $(LDFLAGS_IMAGESOURCE) $(LDFLAGS_GRAPH) $(LDFLAGS_APRIL_LCMTYPES) $(LDFLAGS_CAMERA)
DEPS := $(DEPS_STD) $(DEPS_VX) $(DEPS_APRILTAG) $(DEPS_IMAGESOURCE) $(DEPS_GRAPH) $(DEPS_APRIL_LCMTYPES) $(DEPS_CAMERA)

include $(BUILD_COMMON)

all: $(TARGET)
	@/bin/true

$(TARGET): $(OBJS) $(DEPS)
	@$(LD) -o $@ $^ $(LDFLAGS)

clean:
	@rm -rf *.o $(OBJS) $(TARGET)
