include $(APRIL_PATH)/src/alarm_monitor/Rules.mk
include $(APRIL_PATH)/src/april_graph/Rules.mk
include $(APRIL_PATH)/src/apriltag/Rules.mk
include $(APRIL_PATH)/src/camera/Rules.mk
include $(APRIL_PATH)/src/common/Rules.mk
include $(APRIL_PATH)/src/ek/Rules.mk
include $(APRIL_PATH)/src/espeak_daemon/Rules.mk
include $(APRIL_PATH)/src/hokuyo/Rules.mk
include $(APRIL_PATH)/src/homepage/Rules.mk
include $(APRIL_PATH)/src/httpd/Rules.mk
include $(APRIL_PATH)/src/imagesource/Rules.mk
include $(APRIL_PATH)/src/kvh/Rules.mk
include $(APRIL_PATH)/src/lcmtypes/Rules.mk
include $(APRIL_PATH)/src/licensify/Rules.mk
include $(APRIL_PATH)/src/procman/Rules.mk
include $(APRIL_PATH)/src/raytracer/Rules.mk
include $(APRIL_PATH)/src/rplidar/Rules.mk
include $(APRIL_PATH)/src/scanmatch/Rules.mk
include $(APRIL_PATH)/src/spy/Rules.mk
include $(APRIL_PATH)/src/ublox/Rules.mk
include $(APRIL_PATH)/src/uterm/Rules.mk
include $(APRIL_PATH)/src/velodyne/Rules.mk
include $(APRIL_PATH)/src/viewer/Rules.mk
include $(APRIL_PATH)/src/vx/Rules.mk
include $(APRIL_PATH)/src/sim/Rules.mk
